
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
binary_sensor: !include bin_sensor.yaml
input_boolean: !include input_boolean.yaml
# switch: !include switches.yaml
input_number: !include input_number.yaml
statistics: statistics.yaml
history_stats: history_stats.yaml
filter: filter.yaml

switch:
  - platform: rfxtrx
    automatic_add: false
    devices:
      0b11000100010101010100:
        name: Prise_DIO_54885


http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

api:

alexa:
  smart_home:
    locale: fr-FR
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret amazon_client_id
    client_secret: !secret amazon_client_secret

mqtt: !include mqtt.yaml

homekit: !include homekit.yaml

sonoff: !include sonoff.yaml

homeassistant:
  packages: !include_dir_named packages

lovelace:
  mode: storage
  dashboards:
    piscine_dashboard:
      mode: yaml
      title: Piscine
      icon: mdi:pool
      show_in_sidebar: true
      filename: dashboard_piscine.yaml