# Declaration des sensors (equivalents virtuels jeedom) --> Envoi info de Jeedom vers HA
sensor:
    - name: "Info Conso Box-Garage"
      state_topic: "Box-Garage/conso/puissance"
      device_class: "power"
      unique_id: puissbox

    - name: "Info Compteur Box-Garage"
      state_topic: "Box-Garage/conso/compteur"
      device_class: "distance"
      unique_id: comptbox

    - name: "Info Total Box-Garage"
      state_topic: "Box-Garage/conso/total"
      device_class: "power"
      unique_id: totalbox

    - name: "Info Temperature Box"
      state_topic: "Box-Garage/conso/temperature"
      device_class: "temperature"
      unique_id: tempbox

    - name: "Info Temperature Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "temperature"
      value_template: "{{value_json.temperature | float}}"
      unique_id: tempboxe+

    - name: "Info Humidité Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "humidity"
      value_template: "{{value_json.humidity | float}}"
      unique_id: humboxe+

    - name: "Info Lumière Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "illuminance"
      value_template: "{{value_json.lux | float}}"
      unique_id: luxboxe+

    - name: "Info NH3 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.nh3 | float}}"
      unique_id: nh3boxe+

    - name: "Info Oxidized Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.oxidised | float}}"
      unique_id: oxiboxe+

    - name: "Info PM1 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm1"
      value_template: "{{value_json.pm1 | float}}"
      unique_id: pm1boxe+

    - name: "Info PM10 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm10"
      value_template: "{{value_json.pm10 | float}}"
      unique_id: pm10boxe+

    - name: "Info PM25 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm25"
      value_template: "{{value_json.pm25 | float}}"
      unique_id: pm25boxe+

    - name: "Info Pressure Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pressure"
      value_template: "{{value_json.pressure | float}}"
      unique_id: pressboxe+

    - name: "Info Reduced Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.reduced | float}}"
      unique_id: redboxe+

    - name: "Info Temperature CPU Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "temperature"
      value_template: "{{value_json.cpu_temperature | float}}"
      unique_id: tempcpuboxe+

    # ==========================
    # CAPTEURS PISCINE (Valeurs)
    # ==========================
    - name: "Piscine Température de l'eau"
      state_topic: "HAPiscine/sensor/pool_water_temperature/state"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      unique_id: temp_piscine

    - name: "Piscine Température Brute"
      state_topic: "HAPiscine/sensor/ezo_hw_temperature/state"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      unique_id: tempbrute_piscine

    - name: "Piscine ORP (RedOx Lissée)"
      state_topic: "HAPiscine/sensor/orp_mean/state"
      unit_of_measurement: "mV"
      state_class: measurement
      unique_id: orp_piscine

    - name: "Piscine pH (Lissé)"
      state_topic: "HAPiscine/sensor/ph_mean/state"
      state_class: measurement
      unique_id: pH_piscine

    - name: "Piscine FC Estimé"
      state_topic: "HAPiscine/sensor/e_fc/state"
      unit_of_measurement: "ppm"
      state_class: measurement
      unique_id: fc_piscine

    - name: "Piscine Saisie Manuelle FC"
      state_topic: "HAPiscine/input_number/manual_fc/state"
      unit_of_measurement: "ppm"
      state_class: measurement
      unique_id: manual_fc_piscine

    - name: "Piscine Date Mesure FC"
      state_topic: "HAPiscine/input_datetime/manual_fc_date/state"
      icon: mdi:calendar-clock
      unique_id: date_fc_piscine

    - name: "Piscine Cycles Restants"
      state_topic: "HAPiscine/sensor/remain_cycles/state"
      state_class: measurement
      icon: mdi:sync
      unique_id: cycles_restants_piscine

    - name: "Piscine Niveau Cuve Acide"
      state_topic: "HAPiscine/sensor/muriatic_tank/state"
      unit_of_measurement: "L"
      state_class: measurement
      icon: mdi:barrel
      unique_id: cuve_acide_piscine

    - name: "Piscine État du Cycle Actuel"
      state_topic: "HAPiscine/sensor/pump_state/state"
      icon: mdi:water-pump
      unique_id: cycle_mode_piscine

binary_sensor:

    - name: "Info Lum Chb-Art"
      state_topic: "Chb-Art/Prise/Etat"
      device_class: "Light"
      unique_id: lumart

    - name: "Info Lum Chb-Elliot"
      state_topic: "Chb-Elliot/Prise/Etat"
      device_class: "Light"
      unique_id: lumelliot

    - name: "Info Radiateur Box"
      state_topic: "Box-Garage/Bureau/Radiateur"
      device_class: "Heat"
      unique_id: boxburrad

    # ==========================
    # ÉTATS LOGIQUES PISCINE
    # ==========================
    - name: "Piscine Relais Pompe (HW)"
      state_topic: "HAPiscine/switch/pump_hw/state"
      payload_on: "on"
      payload_off: "off"
      icon: mdi:power-plug
      unique_id: pump_hw_piscine

    - name: "Piscine Relais Robot (HW)"
      state_topic: "HAPiscine/switch/turbo_hw/state"
      payload_on: "on"
      payload_off: "off"
      icon: mdi:power-plug
      unique_id: turbo_hw_piscine

    - name: "Piscine Injection Acide (HW)"
      state_topic: "HAPiscine/switch/ph_hw/state"
      payload_on: "on"
      payload_off: "off"
      icon: mdi:pump
      unique_id: injecteur_acide_piscine

    - name: "Piscine Électrolyseur (HW)"
      state_topic: "HAPiscine/switch/orp_hw/state"
      payload_on: "on"
      payload_off: "off"
      icon: mdi:lightning-bolt
      unique_id: electrolyseur_piscine

    - name: "Piscine État Alerte Acide"
      state_topic: "HAPiscine/binary_sensor/muriatic/state"
      payload_on: "on"
      payload_off: "off"
      device_class: problem
      unique_id: alerte_acide_piscine

    - name: "Piscine État Alerte Électrolyseur"
      state_topic: "HAPiscine/binary_sensor/bleach/state"
      payload_on: "on"
      payload_off: "off"
      device_class: problem
      unique_id: alerte_electrolyseur_piscine
<<<<<<< HEAD
 
=======

>>>>>>> 9debef2 (Update MQTT)
#Declaration des etats et modules de commande entre Jeedom et HA --> Pilotage Jeedom via HA
switch:
  - name: "Lumiere Ext Parking"
    command_topic: "Bureau_Buanderie/lumiere/set"
    state_topic: "Bureau_Buanderie/lumiere/state"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: false
