sensor:
    - name: "Info Conso Box-Garage"
      state_topic: "Box-Garage/conso/puissance"
      device_class: "power"
      unique_id: puissbox

    - name: "Info Compteur Box-Garage"
      state_topic: "Box-Garage/conso/compteur"
      device_class: "distance"
      unique_id: comptbox

    - name: "Info Total Box-Garage"
      state_topic: "Box-Garage/conso/total"
      device_class: "power"
      unique_id: totalbox

    - name: "Info Temperature Box"
      state_topic: "Box-Garage/conso/temperature"
      device_class: "temperature"
      unique_id: tempbox

    - name: "Info Temperature Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "temperature"
      value_template: "{{value_json.temperature | float(0)}}"
      unique_id: tempboxe+

    - name: "Info Humidité Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "humidity"
      value_template: "{{value_json.humidity | float(0)}}"
      unique_id: humboxe+

    - name: "Info Lumière Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "illuminance"
      value_template: "{{value_json.lux | float(0)}}"
      unique_id: luxboxe+

    - name: "Info NH3 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.nh3 | float(0)}}"
      unique_id: nh3boxe+

    - name: "Info Oxidized Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.oxidised | float(0)}}"
      unique_id: oxiboxe+

    - name: "Info PM1 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm1"
      value_template: "{{value_json.pm1 | float(0)}}"
      unique_id: pm1boxe+

    - name: "Info PM10 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm10"
      value_template: "{{value_json.pm10 | float(0)}}"
      unique_id: pm10boxe+

    - name: "Info PM25 Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pm25"
      value_template: "{{value_json.pm25 | float(0)}}"
      unique_id: pm25boxe+

    - name: "Info Pressure Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "pressure"
      value_template: "{{value_json.pressure | float(0)}}"
      unique_id: pressboxe+

    - name: "Info Reduced Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "nitrous_oxide"
      value_template: "{{value_json.reduced | float(0)}}"
      unique_id: redboxe+

    - name: "Info Temperature CPU Box Env+"
      state_topic: "Box-Garage/Bureau/Enviroplus"
      device_class: "temperature"
      value_template: "{{value_json.cpu_temperature | float(0)}}"
      unique_id: tempcpuboxe+

    # ==========================
# CAPTEURS PISCINE (Nouveaux)
# ==========================
    - name: "Piscine Cummulated Flow Start"
      state_topic: "ha/piscine/input_datetime/cummulated_flow_start/state"
      unique_id: input_datetime_cummulated_flow_start_piscine

    - name: "Piscine Cycle Start"
      state_topic: "ha/piscine/input_datetime/cycle_start/state"
      unique_id: input_datetime_cycle_start_piscine

    - name: "Piscine Recirculation"
      state_topic: "ha/piscine/input_datetime/recirculation/state"
      unique_id: input_datetime_recirculation_piscine

    - name: "Piscine Robot Cycle Start"
      state_topic: "ha/piscine/input_datetime/robot_cycle_start/state"
      unique_id: input_datetime_robot_cycle_start_piscine

    - name: "Piscine Second Cycle Start"
      state_topic: "ha/piscine/input_datetime/second_cycle_start/state"
      unique_id: input_datetime_second_cycle_start_piscine

    - name: "Piscine Bleach Concentration"
      state_topic: "ha/piscine/input_number/bleach_concentration/state"
      unique_id: input_number_bleach_concentration_piscine

    - name: "Piscine Bleach Inject"
      state_topic: "ha/piscine/input_number/bleach_inject/state"
      unique_id: input_number_bleach_inject_piscine

    - name: "Piscine Bleach Speed"
      state_topic: "ha/piscine/input_number/bleach_speed/state"
      unique_id: input_number_bleach_speed_piscine

    - name: "Piscine Capacity"
      state_topic: "ha/piscine/input_number/capacity/state"
      unique_id: input_number_capacity_piscine

    - name: "Piscine Cycle"
      state_topic: "ha/piscine/input_number/cycle/state"
      unique_id: input_number_cycle_piscine

    - name: "Piscine E Fc Adjust"
      state_topic: "ha/piscine/input_number/e_fc_adjust/state"
      unique_id: input_number_e_fc_adjust_piscine

    - name: "Piscine Fc Target"
      state_topic: "ha/piscine/input_number/fc_target/state"
      unique_id: input_number_fc_target_piscine

    - name: "Piscine Muriatic Concentration"
      state_topic: "ha/piscine/input_number/muriatic_concentration/state"
      unique_id: input_number_muriatic_concentration_piscine

    - name: "Piscine Muriatic Inject"
      state_topic: "ha/piscine/input_number/muriatic_inject/state"
      unique_id: input_number_muriatic_inject_piscine

    - name: "Piscine Muriatic Speed"
      state_topic: "ha/piscine/input_number/muriatic_speed/state"
      unique_id: input_number_muriatic_speed_piscine

    - name: "Piscine Muriatic Tank"
      state_topic: "ha/piscine/input_number/muriatic_tank/state"
      unique_id: input_number_muriatic_tank_piscine

    - name: "Piscine Notify Bleach High"
      state_topic: "ha/piscine/input_number/notify_bleach_high/state"
      unique_id: input_number_notify_bleach_high_piscine

    - name: "Piscine Notify Cycles"
      state_topic: "ha/piscine/input_number/notify_cycles/state"
      unique_id: input_number_notify_cycles_piscine

    - name: "Piscine Notify Muriatic High"
      state_topic: "ha/piscine/input_number/notify_muriatic_high/state"
      unique_id: input_number_notify_muriatic_high_piscine

    - name: "Piscine Notify Muriatic Tank"
      state_topic: "ha/piscine/input_number/notify_muriatic_tank/state"
      unique_id: input_number_notify_muriatic_tank_piscine

    - name: "Piscine Out Of Order"
      state_topic: "ha/piscine/input_number/out_of_order/state"
      unique_id: input_number_out_of_order_piscine

    - name: "Piscine Javel Pump Flow"
      state_topic: "ha/piscine/input_number/javel_pump_flow/state"
      unique_id: input_number_javel_pump_flow_piscine

    - name: "Piscine Javel Concentration"
      state_topic: "ha/piscine/input_number/javel_concentration/state"
      unique_id: input_number_javel_concentration_piscine

    - name: "Piscine Javel Max Daily Vol"
      state_topic: "ha/piscine/input_number/javel_max_daily_vol/state"
      unique_id: input_number_javel_max_daily_vol_piscine

    - name: "Piscine Javel Max Daily Time"
      state_topic: "ha/piscine/input_number/javel_max_daily_time/state"
      unique_id: input_number_javel_max_daily_time_piscine

    - name: "Piscine Ph Target"
      state_topic: "ha/piscine/input_number/ph_target/state"
      unique_id: input_number_ph_target_piscine

    - name: "Piscine Pump On For"
      state_topic: "ha/piscine/input_number/pump_on_for/state"
      unique_id: input_number_pump_on_for_piscine

    - name: "Piscine Quality"
      state_topic: "ha/piscine/input_number/quality/state"
      unique_id: input_number_quality_piscine

    - name: "Piscine Robot Solar Max Minutes"
      state_topic: "ha/piscine/input_number/robot_solar_max_minutes/state"
      unique_id: input_number_robot_solar_max_minutes_piscine

    - name: "Piscine Second Cycle"
      state_topic: "ha/piscine/input_number/second_cycle/state"
      unique_id: input_number_second_cycle_piscine

    - name: "Piscine Sim Orp"
      state_topic: "ha/piscine/input_number/sim_orp/state"
      unique_id: input_number_sim_orp_piscine

    - name: "Piscine Sim Outdoor Temperature"
      state_topic: "ha/piscine/input_number/sim_outdoor_temperature/state"
      unique_id: input_number_sim_outdoor_temperature_piscine

    - name: "Piscine Sim Ph"
      state_topic: "ha/piscine/input_number/sim_ph/state"
      unique_id: input_number_sim_ph_piscine

    - name: "Piscine Sim Power Consumption"
      state_topic: "ha/piscine/input_number/sim_power_consumption/state"
      unique_id: input_number_sim_power_consumption_piscine

    - name: "Piscine Sim Power Production"
      state_topic: "ha/piscine/input_number/sim_power_production/state"
      unique_id: input_number_sim_power_production_piscine

    - name: "Piscine Sim Temperature"
      state_topic: "ha/piscine/input_number/sim_temperature/state"
      unique_id: input_number_sim_temperature_piscine

    - name: "Piscine Turbo"
      state_topic: "ha/piscine/input_number/turbo/state"
      unique_id: input_number_turbo_piscine

    - name: "Piscine Disinfection Mode"
      state_topic: "ha/piscine/input_select/disinfection_mode/state"
      unique_id: input_select_disinfection_mode_piscine

    - name: "Piscine Pool Mode"
      state_topic: "ha/piscine/input_select/pool_mode/state"
      unique_id: input_select_pool_mode_piscine

    - name: "Piscine Consommation Electrique"
      state_topic: "ha/piscine/sensor/consommation_electrique/state"
      unique_id: sensor_consommation_electrique_piscine

    - name: "Piscine Cummulated Flow High"
      state_topic: "ha/piscine/sensor/cummulated_flow_high/state"
      unique_id: sensor_cummulated_flow_high_piscine

    - name: "Piscine Cummulated Flow Low"
      state_topic: "ha/piscine/sensor/cummulated_flow_low/state"
      unique_id: sensor_cummulated_flow_low_piscine

    - name: "Piscine Cycle Pool"
      state_topic: "ha/piscine/sensor/cycle_pool/state"
      unique_id: sensor_cycle_pool_piscine

    - name: "Piscine Duree Marche Cellule"
      state_topic: "ha/piscine/sensor/duree_marche_cellule/state"
      unique_id: sensor_duree_marche_cellule_piscine

    - name: "Piscine Duree Marche Cellule Effective"
      state_topic: "ha/piscine/sensor/duree_marche_cellule_effective/state"
      unique_id: sensor_duree_marche_cellule_effective_piscine

    - name: "Piscine E Fc"
      state_topic: "ha/piscine/sensor/e_fc/state"
      unique_id: sensor_e_fc_piscine

    - name: "Piscine Ezo Hw Orp"
      state_topic: "ha/piscine/sensor/ezo_hw_orp/state"
      unique_id: sensor_ezo_hw_orp_piscine

    - name: "Piscine Ezo Hw Ph"
      state_topic: "ha/piscine/sensor/ezo_hw_ph/state"
      unique_id: sensor_ezo_hw_ph_piscine

    - name: "Piscine Ezo Hw Temperature"
      state_topic: "ha/piscine/sensor/ezo_hw_temperature/state"
      unique_id: sensor_ezo_hw_temperature_piscine

    - name: "Piscine Muriatic Tank"
      state_topic: "ha/piscine/sensor/muriatic_tank/state"
      unique_id: sensor_muriatic_tank_piscine

    - name: "Piscine Net Power"
      state_topic: "ha/piscine/sensor/net_power/state"
      unique_id: sensor_net_power_piscine

    - name: "Piscine Orp Mean"
      state_topic: "ha/piscine/sensor/orp_mean/state"
      unique_id: sensor_orp_mean_piscine

    - name: "Piscine Ph Mean"
      state_topic: "ha/piscine/sensor/ph_mean/state"
      unique_id: sensor_ph_mean_piscine

    - name: "Piscine Pool Water Temperature"
      state_topic: "ha/piscine/sensor/pool_water_temperature/state"
      unique_id: sensor_pool_water_temperature_piscine

    - name: "Piscine Production Solaire"
      state_topic: "ha/piscine/sensor/production_solaire/state"
      unique_id: sensor_production_solaire_piscine

    - name: "Piscine Pump State"
      state_topic: "ha/piscine/sensor/pump_state/state"
      unique_id: sensor_pump_state_piscine

    - name: "Piscine Remain Cycles"
      state_topic: "ha/piscine/sensor/remain_cycles/state"
      unique_id: sensor_remain_cycles_piscine

    - name: "Piscine Zlt 75 Run Duration"
      state_topic: "ha/piscine/sensor/zlt_75_run_duration/state"
      unique_id: sensor_zlt_75_run_duration_piscine

    - name: "Piscine Javel On Last 24H"
      state_topic: "ha/piscine/sensor/javel_on_last_24h/state"
      unique_id: sensor_javel_on_last_24h_piscine

    - name: "Piscine Javel Volume Ml"
      state_topic: "ha/piscine/sensor/javel_volume_ml/state"
      unique_id: sensor_javel_volume_ml_piscine

    - name: "Piscine Javel Run Duration"
      state_topic: "ha/piscine/sensor/javel_run_duration/state"
      unique_id: sensor_javel_run_duration_piscine

    - name: "Piscine Javel Vol Last 24H"
      state_topic: "ha/piscine/sensor/javel_vol_last_24h/state"
      unique_id: sensor_javel_vol_last_24h_piscine

    

binary_sensor:

    - name: "Info Lum Chb-Art"
      state_topic: "Chb-Art/Prise/Etat"
      device_class: "Light"
      unique_id: lumart

    - name: "Info Lum Chb-Elliot"
      state_topic: "Chb-Elliot/Prise/Etat"
      device_class: "Light"
      unique_id: lumelliot

    - name: "Info Radiateur Box"
      state_topic: "Box-Garage/Bureau/Radiateur"
      device_class: "Heat"
      unique_id: boxburrad

    
    # ==========================
# BINARY SENSORS PISCINE (Nouveaux)
    # ==========================
    - name: "Piscine Bleach"
      state_topic: "ha/piscine/binary_sensor/bleach/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_bleach_piscine

    - name: "Piscine Flowd"
      state_topic: "ha/piscine/binary_sensor/flowd/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_flowd_piscine

    - name: "Piscine Muriatic"
      state_topic: "ha/piscine/binary_sensor/muriatic/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_muriatic_piscine

    - name: "Piscine Power Excess"
      state_topic: "ha/piscine/binary_sensor/power_excess/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_power_excess_piscine

    - name: "Piscine Power Shortage"
      state_topic: "ha/piscine/binary_sensor/power_shortage/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_power_shortage_piscine

    - name: "Piscine Lock Bleach"
      state_topic: "ha/piscine/input_boolean/lock_bleach/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_lock_bleach_piscine

    - name: "Piscine Lock Javel"
      state_topic: "ha/piscine/input_boolean/lock_javel/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_lock_javel_piscine

    - name: "Piscine Lock Muriatic"
      state_topic: "ha/piscine/input_boolean/lock_muriatic/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_lock_muriatic_piscine

    - name: "Piscine Notify Seasson"
      state_topic: "ha/piscine/input_boolean/notify_seasson/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_notify_seasson_piscine

    - name: "Piscine Robot Demarrage Solaire"
      state_topic: "ha/piscine/input_boolean/robot_demarrage_solaire/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_robot_demarrage_solaire_piscine

    - name: "Piscine Sim Flowd"
      state_topic: "ha/piscine/input_boolean/sim_flowd/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_sim_flowd_piscine

    - name: "Piscine Sim Orp Pump"
      state_topic: "ha/piscine/input_boolean/sim_orp_pump/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_sim_orp_pump_piscine

    - name: "Piscine Sim Ph Pump"
      state_topic: "ha/piscine/input_boolean/sim_ph_pump/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_sim_ph_pump_piscine

    - name: "Piscine Sim Pump"
      state_topic: "ha/piscine/input_boolean/sim_pump/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_sim_pump_piscine

    - name: "Piscine Sim Turbo"
      state_topic: "ha/piscine/input_boolean/sim_turbo/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_sim_turbo_piscine

    - name: "Piscine Simulation Mode"
      state_topic: "ha/piscine/input_boolean/simulation_mode/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_simulation_mode_piscine

    - name: "Piscine Turbo"
      state_topic: "ha/piscine/input_boolean/turbo/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: input_boolean_turbo_piscine

    - name: "Piscine Javel"
      state_topic: "ha/piscine/binary_sensor/javel/state"
      payload_on: "on"
      payload_off: "off"
      unique_id: binary_sensor_javel_piscine

    

switch:
    # ==========================
# SWITCHES PISCINE (Nouveaux)
    # ==========================
    - name: "Piscine Electrolyseur Hw"
      state_topic: "ha/piscine/switch/electrolyseur_hw/state"
      command_topic: "ha/piscine/switch/electrolyseur_hw/set"
      payload_on: "on"
      payload_off: "off"
      unique_id: switch_electrolyseur_hw_piscine

    - name: "Piscine Ph Hw"
      state_topic: "ha/piscine/switch/ph_hw/state"
      command_topic: "ha/piscine/switch/ph_hw/set"
      payload_on: "on"
      payload_off: "off"
      unique_id: switch_ph_hw_piscine

    - name: "Piscine Pump Hw"
      state_topic: "ha/piscine/switch/pump_hw/state"
      command_topic: "ha/piscine/switch/pump_hw/set"
      payload_on: "on"
      payload_off: "off"
      unique_id: switch_pump_hw_piscine

    - name: "Piscine Turbo Hw"
      state_topic: "ha/piscine/switch/turbo_hw/state"
      command_topic: "ha/piscine/switch/turbo_hw/set"
      payload_on: "on"
      payload_off: "off"
      unique_id: switch_turbo_hw_piscine

    - name: "Piscine Javel Hw"
      state_topic: "ha/piscine/switch/javel_hw/state"
      command_topic: "ha/piscine/switch/javel_hw/set"
      payload_on: "on"
      payload_off: "off"
      unique_id: switch_javel_hw_piscine
